apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  #名字必须与下面的spec字段匹配，并且格式为 <名称的复数形式>.<组名>
  name: demos.example.com
spec:
  #组名称，用于RESTAPI:/apis/<组>/<版本>
  group: example.com
  names:
    #名称的复数形式，用于URL:/apis/<组>/<版本>/<名称的复数形式>
    plural: demos
    #名称的单数形式，作为命令行使用时和显示时的别名
    singular: demo
    #kind 通常是单数形式的帕斯卡编码形式，你的资源清单会使用这一形式。
    kind: Demo
    #shortnames 允许你在命令行使用较短的字符串来匹配资源
    shortNames:
    - dm
    #可以是namespaced或cluster
  scope: Namespaced
  #列举此customresourcedifinition
  versions:
    - name: v1
      #每个版本都可以通过serverd标志来独立启用或禁止
      served: true
      #其中只有一个且只有一个版本必须被标记为存储版本
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string